name: Build and deploy

on:
  push:
    branches: main

jobs:
  run:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Clone Pages repository
      run: |
        git clone https://${secrets.GITHUB_TOKEN}@github.com/ReverentEngineer/ReverentEngineer.github.io public
    - name: Deploy
      run: ./ci/deploy.sh
