name: Build and deploy

on:
  push:
    branches: main

jobs:
  run:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/checkout@v1
      with: 
        repository: ReverentEngineer/ReverentEngineer.github.io
        ref: master
        path: public
    - name: Deploy
      run: ./ci/deploy.sh
